Practice git 1 son
Steven-fpy/git_study_project pull request #4
Opened 2023-01-30 09:05 UTC by Steven-fpy

test

2023-02-02 02:13 UTC, HyeYeong commented
@Steven-fpy 님
`Arduino/4wd_test/test/test.ino`
이 파일이 아닌... 부모 브랜치에서 변경된 파일인
`Arduino/4wd_test_2/test/test.ino` <- 이 파일을 수정해주세요..!

이 PR 안에서 수정된 Arduino/4wd_test_/test/test.ino <- 이 파일은
reset 으로 커밋을 취소해도 좋고, 변경하기 전 상태를 복사해서 추가로 커밋해도 괜찮습니다.

(원래대로라면 부모 브랜치를 pull해서 작업을 하는 게 좋지만) 이번에는 부모 브랜치를 pull하지 말아주세요!
확인부탁드리겠습니당

2023-02-02 02:14 UTC, HyeYeong requested changes
@Steven-fpy 님
PR 감사합니다. 몇 가지 다시 확인해주세요👍

2023-02-02 02:14 UTC, HyeYeong commented on Python/230130_py.py
> +        break
마지막 1행을 추가해주세요

2023-02-06 07:29 UTC, HyeYeong commented on Python/230130_py.py
> +        break
추가했습니다 3f30106493f550ae52b98dfa13d0ede763d69728

2023-02-07 01:57 UTC, HyeYeong commented
컨플릭트 해결만 부탁드릴게용! ❤️

2023-02-07 06:51 UTC, Steven-fpy commented
conflicts fixed

2023-02-07 06:51 UTC, merged